# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-16 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meldining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='file',
            new_name='imageURL',
        ),
        migrations.RenameField(
            model_name='cuisinetype',
            old_name='file',
            new_name='imageURL',
        ),
    ]
